### PR TITLE
add ability to play short video clips of celebrities

### PR DESCRIPTION
**Pull request by sanzgiri**
add basic functionality to play video clip of selected celebrity.

### CODE REVIEW

**Comment by sanzgiri** [comment]
needs video file (.mp4) to be in the results directory, same place as data bundle. also requires ffmpeg to create clips. creates a 10 sec clip starting 5 sec before timestamp of max score for the selected celebrity.

**Comment by sanzgiri** [comment]
Added changes to support running app in a Docker container.
- Updated README.md with instructions to build & run docker container
- timed.py has a minor change (keeping videos in a separate location from results)
- slight change to run_local.sh to specify separate argument for source and destination paths

**Comment by sanzgiri** [comment]
merged conflicts in timed.py

**Comment by ezavesky** [comment]
Thanks, this makes a great addition to the exploring app!  I added a couple of short cuts to use command line args.  For example, here's my final execution string for our test sample (also updated in README).

```
docker run -it --rm  -p 8501:8501 -e VIDEO=/videos/videohd.mp4 -v ${PWD}/results:/results -v ${PWD}/results:/videos  -v ${PWD}/app:/src/app streamlit_timed:latest
```

**Pull request merged**
